### ISSUE TITLE
Q: Is there a sharing feature?

### ISSUE THREAD

**Issue by mikedolx** [nrocco/bookmarks#14]
Hi,

i have a question. Does you app have a sharing feature?

Can i share a bookmark or list/folder with another user from bookmarks?

Thanks,

BR Mike

**Comment by nrocco** [comment]
Hi @mikedolx,

This app does not have any social features such as sharing.
It's only purpose is to provide an ad free, open source, self hosted to store and search your bookmarks and rss feeds.

**Comment by mikedolx** [comment]
hi @nrocco,

thanks for the response! Just wanted to make things more clear: I'm not looking for a feature to share a link via a social network like Facebook or twitter. 

All i'm looking for is an share option between bookmarks users. I saw from the screenshots, that you can login to bookmarks as a user. So I was wondering if bookmarks userA can share a bookmark with userB.

But if this is not part of the app and maybe shall not be, thats fine for me :-).
