### ISSUE TITLE
Docker exits

### ISSUE THREAD

**Issue by dmhendricks** [nrocco/bookmarks#18]
When I run it as a docker container, it exits right away, only displaying the help text:

```bash
$ docker run -p 3000:3000 nrocco/bookmarks
Personal zero-touch bookmarking app in the cloud, with full text search support.

Usage:
  bookmarks [command]

Available Commands:
  help          Help about any command
...
```

What can I do to get this running as a Docker container rather than a CLI?

Thank you,
Daniel

**Comment by nrocco** [comment]
Hi,

Try the `server` subcommand:

    docker run -p 3000:3000 nrocco/bookmarks bookmarks server

I will see if I can make this the default `CMD` in the `Dockerfile`

**Comment by nrocco** [comment]
I created a PR. 
Closing this issue.
